<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="214181" started-at="2018-02-24T18:30:12Z" finished-at="2018-02-24T18:33:47Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="214181" started-at="2018-02-24T18:30:12Z" finished-at="2018-02-24T18:33:47Z">
      <class name="c2info_ElMob.SalesTC.TC_011_VerifyInvoiceValue">
        <test-method status="PASS" signature="openAPP()[pri:0, instance:c2info_ElMob.SalesTC.TC_011_VerifyInvoiceValue@64bf3bbf]" name="openAPP" is-config="true" duration-ms="62461" started-at="2018-02-25T00:00:12Z" finished-at="2018-02-25T00:01:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openAPP -->
        <test-method status="FAIL" signature="verifyIGSTTax()[pri:0, instance:c2info_ElMob.SalesTC.TC_011_VerifyInvoiceValue@64bf3bbf]" name="verifyIGSTTax" duration-ms="151637" started-at="2018-02-25T00:01:15Z" finished-at="2018-02-25T00:03:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [2750.0] but found [2750.010009765625]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [2750.0] but found [2750.010009765625]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at c2info_ElMob.SalesTC.TC_011_VerifyInvoiceValue.verifyIGSTTax(TC_011_VerifyInvoiceValue.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyIGSTTax -->
      </class> <!-- c2info_ElMob.SalesTC.TC_011_VerifyInvoiceValue -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
